x-db-env:
  environment: &env_db
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_DB: ${POSTGRES_DB:-academy_db}
    POSTGRES_HOST: ${POSTGRES_HOST:-database}

services:
  php:
    container_name: academy-php
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
      target: php_base
    restart: unless-stopped
    environment:
      <<: *env_db
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    networks:
      - test-network
    depends_on:
      - postgresql

  nginx:
    container_name: academy-nginx
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
      target: nginx_base
    restart: unless-stopped
    depends_on:
      - php
      - postgresql
    volumes:
      - ./app/public:/var/www/app/public:ro
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - test-network

  postgresql:
    container_name: academy-psql
    image: postgres:15.2-alpine3.17
    restart: unless-stopped
    environment:
      <<: *env_db
    ports:
      - '5460:5432'
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - test-network

networks:
  test-network:
    external: false
