x-db-env:
  environment: &env_db
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_DB: ${POSTGRES_DB:-academy_db}
    POSTGRES_HOST: ${POSTGRES_HOST:-database}

x-mailer-env:
  environment: &env_mailer
    MAILER_DSN: ${MAILER_DSN}
    MAILER_FROM: ${MAILER_FROM}

x-redis:
  environment: &env_redis
    REDIS_DSN: ${REDIS_DSN:-redis://pass@redis:6379}

services:
  php:
    container_name: academy-php
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
      target: php_base
    restart: unless-stopped
    environment:
      <<:
        [
          *env_db,
          *env_mailer,
          *env_redis
        ]
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    networks:
      - test-network
    depends_on:
      - postgresql
      - redis

  nginx:
    container_name: academy-nginx
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
      target: nginx_base
    restart: unless-stopped
    depends_on:
      - php
      - postgresql
    volumes:
      - ./app/public:/var/www/app/public:ro
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - test-network

  postgresql:
    container_name: academy-psql
    image: postgres:15.2-alpine3.17
    restart: unless-stopped
    environment:
      <<: *env_db
    ports:
      - '5460:5432'
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - test-network

  redis:
    container_name: academy-redis
    image: redis:latest
    restart: unless-stopped
    environment:
      <<: *env_redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - test-network

networks:
  test-network:
    external: false

volumes:
  cache:
    driver: local